more cleanup of scripts and gitignores

diff --git a/bin/cleanup_email_archives b/bin/cleanup_email_archives
--- a/bin/cleanup_email_archives
+++ b/bin/cleanup_email_archives
@@ -1,12 +1,32 @@
 #!/usr/bin/env bash
-cd /opt/saq || exit 1
-source /opt/saq/load_environment
+cd /opt/ace || exit 1
+source load_environment
+
+# XXX this script SUCKS
+
+# brotex streams are on their own so just delete the old ones
+if [ -e archive/smtp_stream ]
+then
+    find -L archive/smtp_stream -mindepth 3 -maxdepth 3 -type f -name '*.tar.gz.gpg' -mmin +480 -delete
+fi
+
+if [ ! -e etc/mysql_defaults.email_archive ]
+then
+    echo "file etc/mysql_defaults.email_archive does not exist - not maintaining email archives"
+    exit 0
+fi
 
 # clear out emails older than 90 days
 # we need to get the server_id in the email archives database
 hostname=$(hostname)
 hostname=${hostname,,}
-server_id=$(mysql --defaults-file=/opt/saq/etc/mysql_defaults.email_archive -r -e "SELECT server_id FROM archive_server WHERE hostname = '$hostname'" | sed -e 's/server_id//g')
+server_id=$(mysql --defaults-file=etc/mysql_defaults.email_archive -r -e "SELECT server_id FROM archive_server WHERE hostname = '$hostname'" | sed -e 's/server_id//g')
+
+if [ -z "${server_id}" ]
+then
+    echo "cannot find database entry for ${hostname}"
+    exit 1
+fi
 
 find -L archive/email/$hostname -mindepth 2 -maxdepth 2 -type f -mtime +90 | while read email
 do
@@ -18,8 +38,6 @@ do
     sql="DELETE FROM archive WHERE server_id = $server_id AND md5 = UNHEX('$md5');"
 
     # delete the index in the database and the email
-    mysql --defaults-file=/opt/saq/etc/mysql_defaults.email_archive -e "$sql" && rm "$email" && echo "delete $email"
+    mysql --defaults-file=etc/mysql_defaults.email_archive -e "$sql" && rm "$email" && echo "delete $email"
 done
 
-# brotex streams are on their own so just delete the old ones
-#find -L archive/smtp_stream -mindepth 3 -maxdepth 3 -type f -name '*.tar.gz.gpg' -mmin +480 -delete
