reset unittest db when installing

diff --git a/bin/reset-unittest-databases b/bin/reset-unittest-databases
--- a/bin/reset-unittest-databases
+++ b/bin/reset-unittest-databases
@@ -4,11 +4,11 @@
 for db in ace ace-workload brocess email-archive hal9000 cloudphish vt-hash-cache
 do
 	echo "resetting db $db-unittest"
-	sudo mysqladmin drop -f $db-unittest > /dev/null
-	sudo mysqladmin create $db-unittest 
-	sudo mysql --database=$db-unittest < sql/$db\_schema.sql
+	mysqladmin drop -f $db-unittest > /dev/null 2>&1
+	mysqladmin create $db-unittest 
+	mysql --database=$db-unittest < sql/$db\_schema.sql
 	if [ -e sql/$db\_init.sql ]
 	then
-		sudo mysql --database=$db-unittest < sql/$db\_init.sql || fail "unable to initialize database $db"
+		mysql --database=$db-unittest < sql/$db\_init.sql || fail "unable to initialize database $db"
 	fi
 done
